In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [18]:
# Read Data
train = pd.read_csv('./input/train.csv')
# test = pd.read_csv('./input/test.csv')


train_data = train.iloc[:5000]




In [19]:
labels = train_data.pop('label')
X_train, X_test, y_train, y_test = train_test_split(train_data, labels, test_size =.2, random_state =0)

In [21]:
# Standardize the Data

Std_Scaler = StandardScaler()
Std_Scaler.fit(X_train)
X_train_std = Std_Scaler.transform(X_train)
X_test_std = Std_Scaler.transform(X_test)

y_train = y_train.values





/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  


In [22]:
# Multinomial Logistic Regression
lgRg = LogisticRegression(multi_class='multinomial',
                         penalty='l1', solver='saga', tol=0.0001)
lgRg.fit(X_train_std, y_train)
y = lgRg.predict(X_test_std)

# Submission
# submission = pd.DataFrame({"ImageId": range(1,y.shape[0]+1),
#     "label": y})

# submission.to_csv("submission_Logistic.csv", index=False)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [25]:
lgRg.score(X_test_std,y_test)

0.886

In [15]:
print(y[:5])

[2 0 9 7 3]


In [13]:
print(y)

[2 0 9 ..., 3 9 2]


IndexError: tuple index out of range

In [16]:
print(X)

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [18]:
print(X.shape)

(42000, 784)


In [26]:
lgRg.get_params([])

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'max_iter': 100,
 'multi_class': 'multinomial',
 'n_jobs': 1,
 'penalty': 'l1',
 'random_state': None,
 'solver': 'saga',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [33]:
lgRg.coef_.shape


(10, 784)

In [4]:
lgRg.coef_[1:]


array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [5]:
test.shape

(28000, 784)

In [18]:
x_std?

In [41]:
lgRg.predict(x_std[0:5,:])

array([2, 0, 9, 7, 3])

In [46]:
test[1,:]

TypeError: unhashable type: 'slice'

In [48]:
train.iloc[1].as_matrix().reshape(28,28)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  18,  30, 137,
        137, 192,  86,  72,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  13,  86, 250, 254, 254,
        254, 254, 217, 246, 151,  32,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [54]:
lgRg.predict_proba(x_std[0:2,:])

array([[  6.50814306e-06,   8.42454469e-10,   9.99991565e-01,
          1.82775945e-06,   3.99960937e-10,   1.07594614e-08,
          6.73547383e-09,   1.18595454e-08,   6.43405784e-08,
          4.11397560e-09],
       [  9.99378157e-01,   2.15073131e-07,   9.85986306e-06,
          2.18266156e-07,   4.64525609e-11,   6.00326116e-04,
          7.26708093e-06,   3.89999435e-06,   5.57801206e-08,
          1.12011241e-09]])

In [56]:
lgRg.predict(x_std[0:2,:])

array([2, 0])

In [59]:
x_std.dtype


dtype('float64')

In [62]:
x_std.shape

(28000, 784)